# Generated by Django 4.0 on 2021-12-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(default=None, max_length=280)),
                ('date_created', models.DateTimeField()),
                ('time_created', models.TimeField()),
                ('username', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
