# Generated by Django 4.0 on 2021-12-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='time_created',
        ),
    ]
